<a href="https://colab.research.google.com/github/hida0/Python_MachineLearning/blob/sklearn/sklearn_1_%EC%A0%84%EC%B2%98%EB%A6%AC_%EA%B8%B0%EB%B3%B8_%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B6%84%ED%95%A0_%EA%B2%B0%EC%B8%A1%EC%B9%98_%ED%98%95%EB%B3%80%ED%99%98_%EC%9B%90%ED%95%AB%EC%9D%B8%EC%BD%94%EB%94%A9_%EC%A0%95%EA%B7%9C%ED%99%94_%ED%91%9C%EC%A4%80%ED%99%94.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 머신러닝의 방법
*   **모델의 선언**
*   **fit**(모델 학습)
*   **predict**(예측)




In [ ]:
import numpy as np

In [ ]:
x = np.arange(10).reshape(-1, 1) # 1열의 차원으로 만들며 행은 존재하는 데이터의 값을 통해 자동으로 지정
x # 10행 1열

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [ ]:
y = (2*x + 1).reshape(-1, 1)
y

array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11],
       [13],
       [15],
       [17],
       [19]])

**reshape()**: 배열의 차원을 지정한 값으로 재설정

-1 값은 지정된 다른 값과 존재하는 데이터 수를 고려하여 자동으로 지정되게 한다.

### step 1: 모델의 선언

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
# 모델 선언
model = LinearRegression()

### step 2: fit(모델의 학습)



In [ ]:
# 학습
model.fit(x, y)

LinearRegression()

### step 3: predict(예측)

In [ ]:
# 예측
prediction = model.predict([[10.0],
                            [11.0]])

In [ ]:
prediction

array([[21.],
       [23.]])

In [ ]:
import numpy as np
import pandas as pd

## 데이터 셋: 타이타닉 데이터셋 (출처: Kaggle.com)

In [ ]:
train = pd.read_csv('https://bit.ly/fc-ml-titanic')

In [ ]:
train.head()

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

* PassengerId: 승객 아이디
* Survived: 생존 여부, 1: 생존, 0: 사망
* Pclass: 등급
* Name: 성함
* Sex: 성별
* Age: 나이
* SibSp: 형제, 자매, 배우자 수
* Parch: 부모, 자식 수
* Ticket: 티켓번호
* Fare: 요즘
* Cabin: 좌석번호
* Embarked: 탑승 항구

## 전처리 1. train / validation 세트 나누기

1. 먼저 **feature 와 label**을 정의합니다.
2. feature / label을 정의했으면 적절한 비율로 train 데이터로부터 **train / validation** set을 나눕니다.


In [ ]:
# 변수로 사용할 column을 list 형식으로 feature로 정의
feature = [
    'Pclass', 'Sex', 'Age', 'Fare'
]

In [ ]:
# 변수로 사용할 column을 list 형식으로 label로 정의
label = [
    'Survived'
]

In [ ]:
train[feature].head()

Pclass     Sex   Age     Fare
0       3    male  22.0   7.2500
1       1  female  38.0  71.2833
2       3  female  26.0   7.9250
3       1  female  35.0  53.1000
4       3    male  35.0   8.0500

In [ ]:
train[label].head()

Survived
0         0
1         1
2         1
3         1
4         0

train / validation set을 나누기 위해 **sklearn.model_selection**에서 필요한 모듈 **train_test_split()**을 임포트한다.

In [ ]:
from sklearn.model_selection import train_test_split

* **test_size**: validation set에 할당할 비율 (20% -> 0.2)
* **shuffle**: 셔플 옵션 (기본 True)
* **random_state**: 랜덤 시드값

return받는 데이터의 **순서**가 중요합니다.

**x_train**(훈련할변수), **x_valid**(검증할 변수), **y_train**(훈련할 변수), **y_valid**(검증할 변수)

In [ ]:
x_train, x_valid, y_train, y_valid = train_test_split(train[feature], train[label], test_size=0.2, shuffle=True, random_state=30)

In [ ]:
(712+179)*0.2

178.20000000000002

In [ ]:
x_train.shape, y_train.shape # 80%

((712, 4), (712, 1))

In [ ]:
x_valid.shape, y_valid.shape # 20%

((179, 4), (179, 1))

## 전처리 2. 결측치 처리

In [ ]:
train = pd.read_csv('https://bit.ly/fc-ml-titanic')

In [ ]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


pandas의 **isnull()**을 통해 결측치를 확인하고

합계를 구하는 **sum()**을 통해 결측치의 개수를 한 눈에 확인할 수 있습니다.

In [ ]:
train.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

개별 column의 결측치에 대하여 확인하는 방법은 다음과 같습니다.

In [ ]:
train['Age'].isnull().sum()

177

[Impute 도큐먼트](https://scikit-learn.org/stable/modules/impute.html)

### 2-1. **수치형(Numerical Column)** 데이터에 대한 결측치 처리

#### 1개의 coulmn을 처리할 때: **fillna()**를 사용
결측치에 적절한 값을 대입한다.

In [ ]:
train['Age'].fillna(0)

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ... 
886    27.0
887    19.0
888     0.0
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

describe()를 통해 결측값을 채운 후의 통계값들을 확인

In [ ]:
train['Age'].fillna(0).describe()

count    891.000000
mean      23.799293
std       17.596074
min        0.000000
25%        6.000000
50%       24.000000
75%       35.000000
max       80.000000
Name: Age, dtype: float64

In [ ]:
# 결측값에 train['Age'].mean()을 대입
train['Age'].fillna(train['Age'].mean()).describe()

count    891.000000
mean      29.699118
std       13.002015
min        0.420000
25%       22.000000
50%       29.699118
75%       35.000000
max       80.000000
Name: Age, dtype: float64

#### 2개 이상의 column을 한 번에 처리할 때: **imputer** 사용
먼저 sklearn.imputer로부터 모듈 **SimpleImputer** 을 임포트한다.

In [ ]:
from sklearn.impute import SimpleImputer

결측값을 무엇으로 처리할 것인지는 **strategy**에 지정한다.

In [ ]:
# 모델의 선언, 결측치를 평균값으로 처리
imputer = SimpleImputer(strategy='mean')

**fit()** 을 통해 결측치에 대한 학습을 진행한다.

In [ ]:
imputer.fit(train[['Age', 'Pclass']])

SimpleImputer()

**transform()** 은 실제 결측치에 대한 처리를 해주는 함수합니다.

In [ ]:
imputer.transform(train[['Age', 'Pclass']])

array([[22.        ,  3.        ],
       [38.        ,  1.        ],
       [26.        ,  3.        ],
       ...,
       [29.69911765,  3.        ],
       [26.        ,  1.        ],
       [32.        ,  3.        ]])

In [ ]:
result = imputer.transform(train[['Age', 'Pclass']])
train[['Age', 'Pclass']] = result # 원래 데이터에 저장

In [ ]:
# 결측값 처리 후 결측값 개수 확인
train[['Age', 'Pclass']].isnull().sum()

Age       0
Pclass    0
dtype: int64

In [ ]:
# 결측값 처리 후 통계값 확인
train[['Age', 'Pclass']].describe()

Age      Pclass
count  891.000000  891.000000
mean    29.699118    2.308642
std     13.002015    0.836071
min      0.420000    1.000000
25%     22.000000    2.000000
50%     29.699118    3.000000
75%     35.000000    3.000000
max     80.000000    3.000000

**fit_transform()** 은 fit()과 transform()을 한 번에 해주는 함수입니다.

In [ ]:
train = pd.read_csv('https://bit.ly/fc-ml-titanic')

In [ ]:
train[['Age', 'Pclass']].isnull().sum()

Age       177
Pclass      0
dtype: int64

In [ ]:
# 모델의 선언, 결측치를 중앙값으로 처리
imputer = SimpleImputer(strategy='median')

In [ ]:
result = imputer.fit_transform(train[['Age', 'Pclass']])
train[['Age', 'Pclass']] = result

In [ ]:
train[['Age', 'Pclass']].isnull().sum()

Age       0
Pclass    0
dtype: int64

In [ ]:
train[['Age', 'Pclass']].describe()

Age      Pclass
count  891.000000  891.000000
mean    29.361582    2.308642
std     13.019697    0.836071
min      0.420000    1.000000
25%     22.000000    2.000000
50%     28.000000    3.000000
75%     35.000000    3.000000
max     80.000000    3.000000

### 2-2. **문자형 (Categorical Column)** 데이터에 대한 결측치 처리

In [ ]:
train = pd.read_csv('https://bit.ly/fc-ml-titanic')

#### 1개의 column을 처리하는 경우: **fillna()** 사용

In [ ]:
train['Embarked'].fillna('S')

0      S
1      C
2      S
3      S
4      S
      ..
886    S
887    S
888    S
889    C
890    Q
Name: Embarked, Length: 891, dtype: object

#### 2개 이상의 column을 처리할 때: sklearn.imputer로부터 모듈 **SimpleImputer**을 임포트해서 사용한다.

In [ ]:
# 모델의 선언, 결측치를 최빈값으로 처리
imputer = SimpleImputer(strategy='most_frequent')

In [ ]:
result = imputer.fit_transform(train[['Embarked', 'Cabin']])
train[['Embarked', 'Cabin']] = result

In [ ]:
train[['Embarked', 'Cabin']].isnull().sum()

Embarked    0
Cabin       0
dtype: int64

## 전처리 3. **Label Encoding** : 문자형(categorical)데이터를 수치형(numerical)데이터로 변환

학습을 위해서 모든 **문자로된 데이터는 수치로 변환**하여야 합니다.

In [ ]:
train = pd.read_csv('https://bit.ly/fc-ml-titanic')

In [ ]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


문자형 데이터를 수치형 데이터로 바꾸기 위해 적용할 함수를 선언

In [ ]:
def convert(data):
    if data == 'male':
        return 1
    elif data == 'female':
        return 0

In [ ]:
train['Sex'].value_counts()

male      577
female    314
Name: Sex, dtype: int64

In [ ]:
train['Sex'].apply(convert)

0      1
1      0
2      0
3      0
4      1
      ..
886    1
887    0
888    0
889    1
890    1
Name: Sex, Length: 891, dtype: int64

**sklearn.preprocessing**로부터 모듈 **LabelEncoder**를 임포트한다.

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
# 모델을 선언
le = LabelEncoder()

In [ ]:
# 모델을 학습시키고 적용하여 새로운 열에 지정
train['Sex_num'] = le.fit_transform(train['Sex'])

In [ ]:
train['Sex_num'].value_counts()

1    577
0    314
Name: Sex_num, dtype: int64

**classes_**를 통해 변환시킨 문자형 column의 구성요소를 확인할 수 있다.

In [ ]:
le.classes_

array(['female', 'male'], dtype=object)

In [ ]:
# 변환시킨 수치형 데이터를 원래의 문자형 데이터로 변환
le.inverse_transform([0, 1, 1, 0, 0, 1, 1])

array(['female', 'male', 'male', 'female', 'female', 'male', 'male'],
      dtype=object)

NaN 값이 포함되어 있다면, `LabelEncoder`가 정상으로 작동하지 않는다.

In [ ]:
le.fit_transform(train['Embarked'])
# Embarked 열은 결측치를 포함하므로 오류 발생

In [ ]:
# fillna()를 통해 결측치를 채우고 다시 저장
train['Embarked'] = train['Embarked'].fillna('S')

In [ ]:
train['Embarked_num'] = le.fit_transform(train['Embarked'])

In [ ]:
train['Embarked_num'].value_counts()

2    646
0    168
1     77
Name: Embarked_num, dtype: int64

## 전처리 4. **원 핫 인코딩** (One Hot Encoding)

In [ ]:
train = pd.read_csv('https://bit.ly/fc-ml-titanic')

In [ ]:
train.head()

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

`Embarked` column을 살펴봅시다.

In [ ]:
train['Embarked'].value_counts()

S    644
C    168
Q     77
Name: Embarked, dtype: int64

In [ ]:
train['Embarked'].isnull().sum() # 2개의 결측치 존재

2

In [ ]:
train['Embarked'] = train['Embarked'].fillna('S') # 결측치에 'S'를 대입
train['Embarked'].value_counts()

S    646
C    168
Q     77
Name: Embarked, dtype: int64

In [ ]:
# 문자형 데이터를 수치형 데이터로 변환하기 위해 필요한 함수
from sklearn.preprocessing import LabelEncoder

In [ ]:
# 모델 선언과 학습 그리고 적용까지 해서 문자형 데이터를 수치형 데이터로 변환한 새로운 열을 지정
train['Embarked_num'] = LabelEncoder().fit_transform(train['Embarked'])

In [ ]:
train['Embarked_num'].value_counts()

2    646
0    168
1     77
Name: Embarked_num, dtype: int64

Embarked는 탑승 항구의 이니셜을 나타냈습니다.

그런데, 우리는 이전에 배운 내용처럼 **`LabelEncoder`**를 통해서 수치형으로 변환해주었습니다.

하지만 이대로 데이터를 기계학습을 시키면 기계는 데이터 안에서 관계를 학습합니다.

즉, 'S' = 2, 'Q' = 1 이라고 되어 있는데 `Q` + `Q` = `S` 가 된다 라고 학습해버린다는 것이죠.

In [ ]:
train['Embarked'][:6]

0    S
1    C
2    S
3    S
4    S
5    Q
Name: Embarked, dtype: object

In [ ]:
train['Embarked_num'][:6]

0    2
1    0
2    2
3    2
4    2
5    1
Name: Embarked_num, dtype: int64

그렇기 때문에 **원 핫 인코딩**을 통해 독립적인 데이터를 별도의 column으로 분리하고,

각각의 컬럼에 해당하는 값에만 **True** 나머지는 **False**를 갖도록 한다.

원 핫 인코딩은 **pandas의 get_dummies()**를 사용한다.

In [ ]:
pd.get_dummies(train['Embarked_num'][:6])

0  1  2
0  0  0  1
1  1  0  0
2  0  0  1
3  0  0  1
4  0  0  1
5  0  1  0

In [ ]:
# 원 핫 인코딩해서 새로운 데이터에 저장
one_hot = pd.get_dummies(train['Embarked_num'][:6])
one_hot

0  1  2
0  0  0  1
1  1  0  0
2  0  0  1
3  0  0  1
4  0  0  1
5  0  1  0

In [ ]:
# 새로운 데이터의 각 columns의 이름을 지정
one_hot.columns = ['C','Q','S']
one_hot

C  Q  S
0  0  0  1
1  1  0  0
2  0  0  1
3  0  0  1
4  0  0  1
5  0  1  0

위와 같이 column을 분리시켜 **문자형을 수치형으로 변환**하면서 생기는 *수치형 값의 관계를 끊어주어서*  **독립적인 형태**로 바꾸어 줍니다.

**원핫인코딩**은 카테고리 (계절, 항구, 성별, 종류, 한식/일식/중식...)의 특성을 가지는 column에 대해서 적용 합니다.

## 전처리 5. **Normalize** (정규화)
column 간에 **다른 min, max** 값을 가지는 경우 정규화를 통해 최소치/ 최대값의 척도를 맞추어 주는 것

* 네이버 영화평점 (0점 ~ 10점): [2, 4, 6, 8, 10]
* 넷플릭스 영화평점 (0점 ~ 5점): [1, 2, 3, 4, 5]

In [ ]:
# dict 생성
movie = {'naver': [2, 4, 6, 8, 10],
         'netflix': [1, 2, 3, 4, 5]
         }

In [ ]:
# dict로부터 데이터프레임을 생성
movie = pd.DataFrame(movie)
movie

naver  netflix
0      2        1
1      4        2
2      6        3
3      8        4
4     10        5

정규화를 하기 위해서 **sklearn.preprocessing**로부터 모듈 **MinMaxScaler**를 임포트한다.

In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
# 모델의 선언
min_max_scaler = MinMaxScaler()

In [ ]:
# 모델을 학습하고 적용하여 새로운 데이터로 저장
min_max_movie = min_max_scaler.fit_transform(movie)
min_max_movie # 배열

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [0.75, 0.75],
       [1.  , 1.  ]])

In [ ]:
# 배열로부터 데이터프레임을 생성
movie_new = pd.DataFrame(min_max_movie)
movie_new

0     1
0  0.00  0.00
1  0.25  0.25
2  0.50  0.50
3  0.75  0.75
4  1.00  1.00

In [ ]:
movie_new.columns = ['naver', 'netflix'] # 바로 movie_new = pd.DataFrame(min_max_movie, columns = ['naver', 'netflix'])로 지정하는 것도 가능
movie_new

naver  netflix
0   0.00     0.00
1   0.25     0.25
2   0.50     0.50
3   0.75     0.75
4   1.00     1.00

## 전처리 6. **표준화** (Standard Scaling)
**평균은 0**, **표준편차는 1**이 되도록 변환한다.

표준화를 하기 위해서는 **sklearn.preprocessing**으로부터 모듈 **StandardScaler**를 임포트한다.

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
# 모델을 선언
standard_scaler = StandardScaler()

샘플데이터를 생성합니다.

In [ ]:
x = np.arange(10)
# outlier 추가
x[9] = 1000
x

array([   0,    1,    2,    3,    4,    5,    6,    7,    8, 1000])

In [ ]:
x.mean(), x.std()

(103.6, 298.8100399919654)

In [ ]:
x_new = x.reshape(-1, 1) # reshape으로 10행 1열의 배열로 차원을 변환

In [ ]:
scaled = standard_scaler.fit_transform(x_new) # reshape으로 10행 1열의 배열로 차원을 변환

In [ ]:
scaled.mean(), scaled.std()

(4.4408920985006264e-17, 1.0)

In [ ]:
round(scaled.mean(), 2), scaled.std()

(0.0, 1.0)